//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bookids
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ModelContainer : DbContext
    {
        public ModelContainer()
            : base("name=ModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Pessoa> Pessoas { get; set; }
        public virtual DbSet<Compra> Compras { get; set; }
        public virtual DbSet<DetalheCompra> DetalhesCompras { get; set; }
        public virtual DbSet<Produto> Produtoes { get; set; }
        public virtual DbSet<Inscrição> Inscrição { get; set; }
        public virtual DbSet<Colaboração> Colaboração { get; set; }
        public virtual DbSet<Evento> Eventoes { get; set; }
        public virtual DbSet<Escola> Escolas { get; set; }
        public virtual DbSet<Participação> Participação { get; set; }
        public virtual DbSet<TipoProduto> TipoProdutos { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
